moblist = ["Ant", "Ladybug", "Bee", "Rock", "Hornet", "Dandelion", "Ant Egg", "Cactus", "Beetle", "Sandstorm", "Fire Ant", "Fire Ant Egg", "Jellyfish", "Leech", "Starfish", "Crab", "Sponge", "Bubble", "Bush", "Dark Ladybug", "Leafbug", "Mantis", "Wasp", "Termite"]
allMobHealth = {
    "Ant": 25,
    "Ladybug": 62,
    "Bee": 37,
    "Rock": 100,
    "Hornet": 62,
    "Dandelion": 25,
    "Ant Egg": 150,
    "Cactus": 75,
    "Beetle": 100,
    "Sandstorm": 125,
    "Fire Ant": 31,
    "Fire Ant Egg": 150,
    "Jellyfish": 125,
    "Leech": 175,
    "Starfish": 150,
    "Crab": 150,
    "Sponge": 100,
    "Bubble": 1,
    "Bush": 25,
    "Dark Ladybug": 87,
    "Leafbug": 50,
    "Mantis": 100,
    "Wasp": 62,
    "Termite": 50
}
allMobDamage = {
    "Ant": 10,
    "Ladybug": 10,
    "Bee": 50,
    "Rock": 10,
    "Hornet": 50,
    "Dandelion": 15,
    "Ant Egg": 3,
    "Cactus": 5,
    "Beetle": 30,
    "Sandstorm": 40,
    "Fire Ant": 20,
    "Fire Ant Egg": 3,
    "Jellyfish": 25,
    "Leech": 10,
    "Starfish": 20,
    "Crab": 25,
    "Sponge": 10,
    "Bubble": 5,
    "Bush": 10,
    "Dark Ladybug": 10,
    "Leafbug": 30,
    "Mantis": 20,
    "Wasp": 50,
    "Termite": 10
}
allPetals = ["Leaf", "Rose", "Stinger", "Rock", "Missile", "Dandelion", "Ant Egg", "Cactus", "Beetle Egg", "Sand", "Yucca", "Ant Egg", "Lightning", "Fangs", "Starfish", "Claw", "Sponge", "Bubble", "Cotton", "Dahila", "Root", "Peas", "Bloodstinger", "Carrot"]
allPetalDamage = {
    "Stinger": 100,
    "Rock": 15,
    "Missile": 25,
    "Dandelion": 5,
    "Ant Egg" 10,
    "Cactus": 5,
    "Beetle Egg": 30,
    "Sand": 20,
    "Ant Egg": 10,
    "Lightning" 12,
    "Claw": 5,
    "Sponge": 0,
    "Bubble": 0,
    "Cotton": 0,
    "Root": 5,
    "Peas": 32,
    "Bloodstinger": 100,
    "Carrot": 10
}
